// Generated by CoffeeScript 1.7.1
(function() {
  var FaceApp,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  FaceApp = (function() {
    function FaceApp(canvas, picture) {
      this.canvas = canvas;
      this.picture = picture;
      this.detectFaces = __bind(this.detectFaces, this);
      this.removeClosest = __bind(this.removeClosest, this);
      this.drawMarkers = __bind(this.drawMarkers, this);
      this.drawMask = __bind(this.drawMask, this);
      this.drawNumbers = __bind(this.drawNumbers, this);
      this.draw = __bind(this.draw, this);
      this.drawEdges = __bind(this.drawEdges, this);
      this.drawImage = __bind(this.drawImage, this);
      this.sortFaces = __bind(this.sortFaces, this);
      this.picture.load((function(_this) {
        return function() {
          var pic;
          pic = _this.picture[0];
          _this.canvas[0].width = pic.naturalWidth;
          _this.canvas[0].height = pic.naturalHeight;
          _this.canvas.width(pic.naturalWidth);
          _this.canvas.height(pic.naturalHeight);
          return _this.drawImage();
        };
      })(this));
      this.ctx = this.canvas[0].getContext('2d');
      this.faces = [];
      this.printView = false;
      this.init();
    }

    FaceApp.prototype.sortFaces = function() {
      var score;
      score = function(face) {
        return face.y * 100 + face.x;
      };
      return this.faces.sort(function(a, b) {
        return score(a) - score(b);
      });
    };

    FaceApp.prototype.drawImage = function() {
      var pic;
      pic = this.picture[0];
      return this.ctx.drawImage(pic, 0, 0);
    };

    FaceApp.prototype.drawEdges = function(edges, style) {
      if (this.faces.length === 0) {
        return;
      }
      this.ctx.lineWidth = 2;
      this.ctx.strokeStyle = style != null ? style : "#0f0";
      this.ctx.beginPath();
      edges.forEach((function(_this) {
        return function(edge) {
          _this.ctx.moveTo(edge.va.x, edge.va.y);
          return _this.ctx.lineTo(edge.vb.x, edge.vb.y);
        };
      })(this));
      return this.ctx.stroke();
    };

    FaceApp.prototype.draw = function(print) {
      var bbox, f, result, sites, voronoi;
      this.ctx.clearRect(0, 0, this.canvas.width(), this.canvas.height());
      this.drawImage();
      if (print) {
        this.drawMask();
      }
      bbox = {
        xl: 0,
        xr: this.canvas.width(),
        yt: 0,
        yb: this.canvas.height()
      };
      voronoi = new Voronoi();
      sites = (function() {
        var _i, _len, _ref, _results;
        _ref = this.faces;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          f = _ref[_i];
          _results.push({
            x: f.x,
            y: f.y
          });
        }
        return _results;
      }).call(this);
      result = voronoi.compute(sites, bbox);
      this.drawEdges(result.edges, print ? "#000" : "#fff");
      if (!print) {
        this.drawMarkers();
      }
      if (print) {
        return this.drawNumbers();
      }
    };

    FaceApp.prototype.drawNumbers = function() {
      var ctx, rect;
      ctx = this.ctx;
      ctx.fillStyle = "#000";
      ctx.font = "20px Sans";
      ctx.textAlign = "center";
      ctx.textBaseline = "middle";
      rect = this.canvas[0].getBoundingClientRect();
      return this.faces.forEach(function(face, idx) {
        return ctx.fillText(idx, face.x, face.y);
      });
    };

    FaceApp.prototype.drawMask = function() {
      this.ctx.fillStyle = "rgba(255,255,255,0.75)";
      return this.ctx.fillRect(0, 0, this.canvas.width(), this.canvas.height());
    };

    FaceApp.prototype.drawMarkers = function() {
      var ctx;
      if (this.faces.length === 0) {
        return;
      }
      ctx = this.ctx;
      ctx.strokeStyle = "#000";
      ctx.lineWidth = 2;
      ctx.fillStyle = "rgba(150,150,255,0.35)";
      return this.faces.forEach(function(face) {
        var w;
        w = 4;
        ctx.beginPath();
        ctx.arc(face.x, face.y, 2 * w, 0, Math.PI * 2, true);
        ctx.fill();
        return ctx.stroke();
      });
    };

    FaceApp.prototype.removeClosest = function(faces, pos) {
      var dist, minDist, minIndex;
      dist = function(a, b) {
        return Math.sqrt((a.x - b.x) * (a.x - b.x) + (a.y - b.y) * (a.y - b.y));
      };
      minIndex = -1;
      minDist = 5 * (this.canvas.width() + this.canvas.height());
      this.faces.forEach(function(face, idx) {
        var d;
        d = dist(face, pos);
        if (d < minDist) {
          minDist = d;
          return minIndex = idx;
        }
      });
      if (minIndex === -1) {
        return;
      }
      return this.faces.splice(minIndex, 1);
    };

    FaceApp.prototype.detectFaces = function(e) {
      e.target.disabled = true;
      return this.picture.faceDetection({
        async: true,
        grayscale: false,
        minNeighbors: 1,
        interval: 8,
        complete: (function(_this) {
          return function(f) {
            f.forEach(function(fc) {
              return _this.faces.push({
                x: (fc.x + fc.width / 2) >> 0,
                y: (fc.y + fc.height / 2) >> 0
              });
            });
            e.target.disabled = false;
            return _this.draw();
          };
        })(this),
        error: function(code, msg) {
          return console.log('Oh no! Error ' + code + ' occurred. The message was "' + msg + '".');
        }
      });
    };

    FaceApp.prototype.init = function() {
      var button, onClick, printButton, toggle;
      button = $('#detectfaces');
      button.prop('disabled', false);
      button.click(this.detectFaces);
      printButton = $('#printview');
      printButton.prop('disabled', false);
      toggle = (function(_this) {
        return function() {
          _this.printView = !_this.printView;
          _this.sortFaces();
          _this.draw(_this.printView);
          return printButton.attr('value', (_this.printView ? "edit" : "print") + " view");
        };
      })(this);
      printButton.click(toggle);
      onClick = (function(_this) {
        return function(e) {
          var cx, cy, rect;
          rect = _this.canvas[0].getBoundingClientRect();
          cx = (e.clientX - rect.left) >> 0;
          cy = (e.clientY - rect.top) >> 0;
          if (e.ctrlKey || e.metaKey) {
            _this.removeClosest(_this.faces, {
              x: cx,
              y: cy
            });
          } else {
            _this.faces.push({
              x: cx,
              y: cy,
              width: 0,
              height: 0
            });
          }
          return _this.draw(_this.printView);
        };
      })(this);
      return this.canvas.click(onClick);
    };

    return FaceApp;

  })();

  $(document).ready(function() {
    return new FaceApp($('#canvas'), $('#picture'));
  });

}).call(this);
