// Generated by CoffeeScript 1.9.2
(function() {
  $(document).ready(function() {
    var areas, names, pointer_radius;
    names = $('#names li');
    areas = $('#facemap area');
    $('#footer').click(function() {
      return $(this).hide();
    });
    pointer_radius = 60;
    $('#pointer').css({
      width: pointer_radius + "px",
      height: pointer_radius + "px",
      "border-radius": pointer_radius + "px"
    });
    names.each(function(index, name) {
      var first, last;
      last = $('span.last', name).text();
      first = $('span.first', name).text();
      if (!last && !first) {
        $(name).html('(Unbekannt)');
      }
      return $(name).hover((function() {
        var area, f, id, image_offset, oleft, otop, x, y;
        $(this).addClass('highlight');
        id = parseInt($(this).attr('data-id'));
        image_offset = $('#faces').offset();
        f = $('#faces');
        area = $('#facemap area[data-id="' + id + '"]');
        oleft = image_offset.left - f.scrollLeft();
        otop = image_offset.top - f.scrollTop();
        x = (parseInt(area.attr('data-x'))) - Math.floor(pointer_radius / 2) + oleft;
        y = (parseInt(area.attr('data-y'))) - Math.floor(pointer_radius / 2) + otop;
        return $('#pointer').css({
          visibility: "visible",
          left: x,
          top: y
        });
      }), (function() {
        $('#pointer').css({
          visibility: "hidden"
        });
        return $(this).removeClass('highlight');
      }));
    });
    return areas.each(function(index, area) {
      var id, name;
      id = parseInt($(this).attr('data-id'));
      name = $("#names li[data-id=\"" + id + "\"]");
      $(this).attr('title', name.text());
      return $(this).hover((function() {
        var container;
        name.addClass('highlight');
        container = $('#names');
        return container.animate({
          scrollTop: name.offset().top - container.offset().top + container.scrollTop()
        }, 32);
      }), (function() {
        return name.removeClass('highlight');
      }));
    });
  });

}).call(this);
